name: Lint

on:
  - workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          version: "~= 24.0"
          jupyter: true
      - uses: isort/isort-action@master
